CREATE TABLE IF NOT EXISTS champions (
    id INT AUTO_INCREMENT PRIMARY KEY,
    name VARCHAR(255) NOT NULL,
    role VARCHAR(255) NOT NULL,
    lore TEXT,
    image_url VARCHAR(255)
);

INSERT INTO champions (name, role, lore, image_url) VALUES
    ('Jinx', 'Atirador', 'Uma criminosa impulsiva e maniaca de Zaun, Jinx vive para disseminar o caos sem se preocupar com as consequencias. Com um arsenal de armas mortais, ela detona as explosoes mais altas e mais luminosas para deixar um rastro de destruicao e panico por onde passa. Jinx abomina o tedio e deixa alegremente sua marca caotica de pandemonio aonde quer que va.', 'https://ddragon.leagueoflegends.com/cdn/img/champion/splash/Jinx_0.jpg'),
    ('Vi', 'Lutador', 'Antiga criminosa das ruas violentas de Zaun, Vi e uma mulher temivel, impulsiva e explosiva que tem muito pouco respeito por autoridades. Apos ter crescido completamente so, Vi desenvolveu instintos de sobrevivencia extremamente certeiros e um senso de humor extremamente acido. Agora trabalhando com os Vigias de Piltover para manter a paz, ela porta poderosas manoplas hextec capazes de esmagar paredes e suspeitos com a mesma facilidade.', 'https://ddragon.leagueoflegends.com/cdn/img/champion/splash/Vi_0.jpg'),
    ('Ekko', 'Assassino', 'Um prodigio das ruas violentas de Zaun, Ekko manipula o tempo para reverter qualquer situacao a seu favor. Usando sua propria invensao, o Revo-Z, ele explora as possiveis bifurcacoes da realidade para criar o momento perfeito. Embora valorize muito sua liberdade, quando algo ameaca seus amigos, ele nao mede esforcos para defende-los. Para meros observadores, Ekko parece conseguir o impossivel sempre de primeira.', 'https://ddragon.leagueoflegends.com/cdn/img/champion/splash/Ekko_0.jpg'),
    ('Caitlyn', 'Atirador', 'Conhecida como sua melhor pacificadora, Caitlyn tambem e a melhor escolha de Piltover para livrar a cidade de seus elementos criminosos elusivos. E comum que ela faca dupla com Vi, agindo como um contraponto de calmaria para a natureza impetuosa de sua parceira. Mesmo carregando um rifle hextec unico, a arma mais poderosa de Caitlyn e seu intelecto superior, que permite que ela prepare elaboradas armadilhas para qualquer fora da lei tolo o suficiente para operar na Cidade do Progresso.', 'https://ddragon.leagueoflegends.com/cdn/img/champion/splash/Caitlyn_0.jpg'),
    ('Jayce', 'Lutador', 'Jayce e um brilhante inventor que dedicou sua vida a defender Piltover e sua implacavel busca pelo progresso. Com seu martelo hextech transformador em maos, Jayce usa sua forca, coragem e consideravel inteligencia para proteger sua cidade natal. Embora seja aclamado pela cidade como heroi, ele nao gosta muito da atencao que o heroismo traz. Mesmo assim, o coracao de Jayce esta no lugar certo e ate aqueles que invejam suas habilidades naturais sao gratos a forma como ele protege a Cidade do Progresso.', 'https://ddragon.leagueoflegends.com/cdn/img/champion/splash/Jayce_0.jpg'),
    ('Viktor', 'Mago', 'Viktor, o arauto de uma nova era de tecnologia, devotou sua vida ao avanco da humanidade. Um idealista que busca elevar o povo de Zaun a um novo nivel de compreensao, ele acredita que somente ao aceitar a evolucao gloriosa da tecnologia sera possivel que a humanidade alcance seu verdadeiro potencial. Com um corpo melhorado por aco e ciencia, Viktor e zeloso na sua busca por este brilhante futuro.', 'https://ddragon.leagueoflegends.com/cdn/img/champion/splash/Viktor_0.jpg'),
    ('Heimerdinger', 'Mago', 'Um cientista brilhante, mesmo que excetrico, o Professor Cecil B. Heimerdinger e um dos inventores mais inovadores e estimados que Piltover ja conheceu. Incansavel em seu trabalho ao ponto da obsessao neurotica, ele busca responder as questoes mais impenetraveis do universo. Apesar de suas teorias frequentemente parecerem obscuras e esotericas, Heimerdinger produziu algumas das maquinas mais miraculosas, sem mencionar letais, de Piltover e ajusta constantemente suas invencoes para torna-las ainda mais eficientes.', 'https://ddragon.leagueoflegends.com/cdn/img/champion/splash/Heimerdinger_0.jpg'),
    ('Singed', 'Tanque', 'Singed e um alquimista zaunita de intelecto inigualavel, que devotou sua vida a ultrapassar os limites do conhecimento; e nenhum preco, nem sua propria sanidade, e alto demais. Existe cura para sua loucura? Suas misturas raramente falham, mas, para muitos, Singed perdeu qualquer nocao da humanidade, deixando uma trilha toxica de miseria e terror no seu caminho.', 'https://ddragon.leagueoflegends.com/cdn/img/champion/splash/Singed_0.jpg'),
    ('Ryze', 'Mago', 'Considerado pela grande maioria como o mago mais habilidoso de Runeterra, Ryze e um arquimago anciao e amargo que carrega um enorme peso. Dotado de um enorme poder arcano e de uma notavel estrutura fisica, ele busca incansavelmente pelas Runas Globais, que sao fragmentos de magia pura que um dia criaram o mundo a partir do nada. Ele deve recuperar esses artefatos antes que eles caiam em maos erradas, pois Ryze conhece bem os horrores que eles podem infligir em Runeterra.', 'https://ddragon.leagueoflegends.com/cdn/img/champion/splash/Ryze_0.jpg'),
    ('Master Yi', 'Assassino', 'Master Yi treinou seu corpo e afiou sua mente para que pensamento e acao se tornassem quase um so. Embora ele prefira recorrer a violencia como ultimo recurso, a leveza e a velocidade de sua espada garantem uma resolucao sempre veloz. Como um dos ultimos praticantes da arte ioniana do Wuju, Yi dedicou sua vida a preservar o legado de seu povo, avaliando potenciais discipulos com as Sete Lentes da Perspicacia para identificar qual deles era o mais digno.', 'https://ddragon.leagueoflegends.com/cdn/img/champion/splash/MasterYi_0.jpg'),
    ('Garen', 'Lutador', 'Um guerreiro nobre e orgulhoso, Garen faz parte da Vanguarda Destemida. Popular entre seus companheiros e respeitado o suficiente por seus inimigos, sua reputacao e nada mais do que o esperado de um herdeiro da prestigiosa familia Stemmaguarda, encarregada de defender Demacia e seus ideais. Vestido com uma armadura resistente a magia e empunhando uma poderosa espada, Garen esta sempre pronto para confrontar magos e feiticeiros no campo de batalha, em um verdadeiro furacao de aco virtuoso.', 'https://ddragon.leagueoflegends.com/cdn/img/champion/splash/Garen_0.jpg'),
    ('Teemo', 'Atirador', 'Indiferente ate aos obstaculos mais perigosos e ameacadores, Teemo vasculha o mundo com infinito entusiasmo e animacao. Um yordle com uma inabalavel moral que se orgulha de seguir o Codigo dos Escoteiros de Bandopolis, as vezes com tanta dedicacao que nao se toca das possiveis consequencias de suas acoes. Embora alguns duvidem da existencia dos escoteiros, uma coisa e certa: nunca se deve duvidar das conviccoes de Teemo.', 'https://ddragon.leagueoflegends.com/cdn/img/champion/splash/Teemo_0.jpg');